<div id="intro">
    <div id="intro_msg">
        <h1>Ready to <span>Test</span> Your <span>Knowledge?</span></h1>
        <p>Dive into fun and <span>challenging</span> quizzes with our app! From general trivia to niche topics, there's something for everyone. Track your progress, challenge friends, and learn new facts – all in one place. Start now and see how much you really know!</p>
    </div>
    <div id="intro_img_cont">
        <div id="intro_img"></div>
        <div id="intro_img_blur"></div>
    </div>
</div>

