<div id="intro">
    <div id="intro_msg">
        <h1>Ready to Test Your <span>Knowledge?</span></h1>
        <p>Dive into fun and challenging quizzes with our app! From general trivia to niche topics, there's something for everyone. Track your progress, challenge friends, and learn new facts – all in one place. Start now and see how much you really know!</p>
    </div>
    <div id="into_img">
        
    </div>
</div>